from fastapi import FastAPI, HTTPException  # noqa: I001
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import requests # type: ignore
import json  # noqa: F401

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    message: str
    grade: str
    subject: str

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3"

@app.post("/chat")
def chat_endpoint(req: ChatRequest):
    try:
        # Construct strict formatting guidelines so responses are structured and readable
        if "Pedagogy" in req.subject:
            system_instruction = (
                "You are an expert academic educator and fact-checker in a Teacher Blackboard Workspace. "
                "Structure your response clearly using Markdown:\n"
                "### 🎯 Core Fact & Concept Breakdown\n"
                "### 📝 Classroom Application / Real-World Example\n"
                "### 💡 Pedagogical Tips for Teachers\n"
                "Keep explanations professional, rigorous, and well-formatted with bullet points."
            )
        elif "School Project Mentorship" in req.subject:
            system_instruction = (
                "You are a supportive school project mentor guiding parents. "
                "Structure your response clearly using Markdown:\n"
                "### 📌 Project Overview & Goals\n"
                "### 🛠️ Materials & Prep Needed\n"
                "### 📅 Step-by-Step Parent Supervision Timeline\n"
                "### ✨ Tips to Make Learning Fun (Without doing it for them)\n"
                "Keep instructions warm, practical, and organized with bullet points."
            )
        else:
            system_instruction = (
                f"You are an engaging AI study partner in the Student Corner. "
                f"Target Student Grade: {req.grade}. Subject Area: {req.subject}. "
                f"Format your response with clear headings or bullet points. "
                f"Explain concepts using simple, accessible language."
            )

        full_prompt = f"{system_instruction}\n\nUser Request: {req.message}\n\nFormatted Response:"

        payload = {
            "model": MODEL_NAME,
            "prompt": full_prompt,
            "stream": False
        }

        # Increased timeout to 180 seconds to give local models enough time to generate structured guides
        response = requests.post(OLLAMA_URL, json=payload, timeout=180)
        
        if response.status_code != 200:
            raise HTTPException(
                status_code=500, 
                detail=f"Ollama returned status code {response.status_code}"
            )

        data = response.json()
        ai_reply = data.get("response", "No response generated by model.")

        return {"reply": ai_reply}

    except requests.exceptions.ConnectionError:
        raise HTTPException(
            status_code=500, 
            detail="Could not connect to Ollama. Make sure Ollama is running locally ('ollama serve')."
        )
    except requests.exceptions.Timeout:
        raise HTTPException(
            status_code=500, 
            detail="Ollama took too long to respond. Try simplifying your prompt or using a smaller model."
        )
    except Exception as e:  # noqa: BLE001
        print(f"Backend Server Error: {str(e)}")  # noqa: RUF010
        raise HTTPException(status_code=500, detail=str(e))